'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
'
Namespace localhost
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ServiceSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ConsultaClientesDSOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultaClientesDS1OperationCompleted As System.Threading.SendOrPostCallback
        
        Private InsertaClientesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ModificaClientesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EliminaClienteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.prjClientesCRM.My.MySettings.Default.prjClientesCRM_localhost_Service
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ConsultaClientesDSCompleted As ConsultaClientesDSCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultaClientesDS1Completed As ConsultaClientesDS1CompletedEventHandler
        
        '''<remarks/>
        Public Event InsertaClientesCompleted As InsertaClientesCompletedEventHandler
        
        '''<remarks/>
        Public Event ModificaClientesCompleted As ModificaClientesCompletedEventHandler
        
        '''<remarks/>
        Public Event EliminaClienteCompleted As EliminaClienteCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaClientesFiltro", RequestElementName:="ConsultaClientesFiltro", RequestNamespace:="http://tempuri.org/", ResponseElementName:="ConsultaClientesFiltroResponse", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Overloads Function ConsultaClientesDS(ByVal sTabla As String, ByVal sCampos As String, ByVal sFiltro As String) As <System.Xml.Serialization.XmlElementAttribute("ConsultaClientesFiltroResult")> System.Data.DataSet
            Dim results() As Object = Me.Invoke("ConsultaClientesDS", New Object() {sTabla, sCampos, sFiltro})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultaClientesDSAsync(ByVal sTabla As String, ByVal sCampos As String, ByVal sFiltro As String)
            Me.ConsultaClientesDSAsync(sTabla, sCampos, sFiltro, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultaClientesDSAsync(ByVal sTabla As String, ByVal sCampos As String, ByVal sFiltro As String, ByVal userState As Object)
            If (Me.ConsultaClientesDSOperationCompleted Is Nothing) Then
                Me.ConsultaClientesDSOperationCompleted = AddressOf Me.OnConsultaClientesDSOperationCompleted
            End If
            Me.InvokeAsync("ConsultaClientesDS", New Object() {sTabla, sCampos, sFiltro}, Me.ConsultaClientesDSOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultaClientesDSOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaClientesDSCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaClientesDSCompleted(Me, New ConsultaClientesDSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.WebMethodAttribute(MessageName:="ConsultaClientesDS1"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaClientesFiltroOrden", RequestElementName:="ConsultaClientesFiltroOrden", RequestNamespace:="http://tempuri.org/", ResponseElementName:="ConsultaClientesFiltroOrdenResponse", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Overloads Function ConsultaClientesDS(ByVal sTabla As String, ByVal sCampos As String, ByVal sFiltro As String, ByVal sOrden As String) As <System.Xml.Serialization.XmlElementAttribute("ConsultaClientesFiltroOrdenResult")> System.Data.DataSet
            Dim results() As Object = Me.Invoke("ConsultaClientesDS1", New Object() {sTabla, sCampos, sFiltro, sOrden})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultaClientesDS1Async(ByVal sTabla As String, ByVal sCampos As String, ByVal sFiltro As String, ByVal sOrden As String)
            Me.ConsultaClientesDS1Async(sTabla, sCampos, sFiltro, sOrden, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultaClientesDS1Async(ByVal sTabla As String, ByVal sCampos As String, ByVal sFiltro As String, ByVal sOrden As String, ByVal userState As Object)
            If (Me.ConsultaClientesDS1OperationCompleted Is Nothing) Then
                Me.ConsultaClientesDS1OperationCompleted = AddressOf Me.OnConsultaClientesDS1OperationCompleted
            End If
            Me.InvokeAsync("ConsultaClientesDS1", New Object() {sTabla, sCampos, sFiltro, sOrden}, Me.ConsultaClientesDS1OperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultaClientesDS1OperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaClientesDS1CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaClientesDS1Completed(Me, New ConsultaClientesDS1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertaClientes", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function InsertaClientes(ByVal sNombre As String, ByVal sDir As String, ByVal sTel As String, ByVal sFax As String, ByVal sNit As String, ByVal sRegFisc As String) As Boolean
            Dim results() As Object = Me.Invoke("InsertaClientes", New Object() {sNombre, sDir, sTel, sFax, sNit, sRegFisc})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub InsertaClientesAsync(ByVal sNombre As String, ByVal sDir As String, ByVal sTel As String, ByVal sFax As String, ByVal sNit As String, ByVal sRegFisc As String)
            Me.InsertaClientesAsync(sNombre, sDir, sTel, sFax, sNit, sRegFisc, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InsertaClientesAsync(ByVal sNombre As String, ByVal sDir As String, ByVal sTel As String, ByVal sFax As String, ByVal sNit As String, ByVal sRegFisc As String, ByVal userState As Object)
            If (Me.InsertaClientesOperationCompleted Is Nothing) Then
                Me.InsertaClientesOperationCompleted = AddressOf Me.OnInsertaClientesOperationCompleted
            End If
            Me.InvokeAsync("InsertaClientes", New Object() {sNombre, sDir, sTel, sFax, sNit, sRegFisc}, Me.InsertaClientesOperationCompleted, userState)
        End Sub
        
        Private Sub OnInsertaClientesOperationCompleted(ByVal arg As Object)
            If (Not (Me.InsertaClientesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InsertaClientesCompleted(Me, New InsertaClientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificaClientes", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ModificaClientes(ByVal nCod As Integer, ByVal sNombre As String, ByVal sDir As String, ByVal sTel As String, ByVal sFax As String, ByVal sNit As String, ByVal sRegFisc As String) As Boolean
            Dim results() As Object = Me.Invoke("ModificaClientes", New Object() {nCod, sNombre, sDir, sTel, sFax, sNit, sRegFisc})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ModificaClientesAsync(ByVal nCod As Integer, ByVal sNombre As String, ByVal sDir As String, ByVal sTel As String, ByVal sFax As String, ByVal sNit As String, ByVal sRegFisc As String)
            Me.ModificaClientesAsync(nCod, sNombre, sDir, sTel, sFax, sNit, sRegFisc, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ModificaClientesAsync(ByVal nCod As Integer, ByVal sNombre As String, ByVal sDir As String, ByVal sTel As String, ByVal sFax As String, ByVal sNit As String, ByVal sRegFisc As String, ByVal userState As Object)
            If (Me.ModificaClientesOperationCompleted Is Nothing) Then
                Me.ModificaClientesOperationCompleted = AddressOf Me.OnModificaClientesOperationCompleted
            End If
            Me.InvokeAsync("ModificaClientes", New Object() {nCod, sNombre, sDir, sTel, sFax, sNit, sRegFisc}, Me.ModificaClientesOperationCompleted, userState)
        End Sub
        
        Private Sub OnModificaClientesOperationCompleted(ByVal arg As Object)
            If (Not (Me.ModificaClientesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ModificaClientesCompleted(Me, New ModificaClientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminaCliente", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EliminaCliente(ByVal nCodClie As Integer) As Boolean
            Dim results() As Object = Me.Invoke("EliminaCliente", New Object() {nCodClie})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EliminaClienteAsync(ByVal nCodClie As Integer)
            Me.EliminaClienteAsync(nCodClie, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EliminaClienteAsync(ByVal nCodClie As Integer, ByVal userState As Object)
            If (Me.EliminaClienteOperationCompleted Is Nothing) Then
                Me.EliminaClienteOperationCompleted = AddressOf Me.OnEliminaClienteOperationCompleted
            End If
            Me.InvokeAsync("EliminaCliente", New Object() {nCodClie}, Me.EliminaClienteOperationCompleted, userState)
        End Sub
        
        Private Sub OnEliminaClienteOperationCompleted(ByVal arg As Object)
            If (Not (Me.EliminaClienteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EliminaClienteCompleted(Me, New EliminaClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub ConsultaClientesDSCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaClientesDSCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultaClientesDSCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub ConsultaClientesDS1CompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaClientesDS1CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultaClientesDS1CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub InsertaClientesCompletedEventHandler(ByVal sender As Object, ByVal e As InsertaClientesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InsertaClientesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub ModificaClientesCompletedEventHandler(ByVal sender As Object, ByVal e As ModificaClientesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ModificaClientesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub EliminaClienteCompletedEventHandler(ByVal sender As Object, ByVal e As EliminaClienteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EliminaClienteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
End Namespace
