Insert into courses(course_name) values('Deploying and Accessing an Application to an AKS Cluster');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Deploy and Run Your First Azure Function');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Configuring Network Interfaces on Linux');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Analyzing Network Traffic on a Linux Host');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Configuring Routing on a Linux Host');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Managing Network Interfaces on a Linux Host');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Deploying an Amazon RDS Multi-AZ and Read Replica');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Restoring an Amazon RDS Instance Using Snapshots');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Creating a DynamoDB Table');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Working with DynamoDB Local and Global Indexes');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Creating an Amazon Aurora RDS Database (MySQL Compatible)');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Creating and Connecting to an Aurora Serverless Database via CLI');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Loading and Retrieving Data in Neptune');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Loading Data into a Redshift Cluster');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Using the AWS DMS to Migrate Data to an Aurora Database');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Migrating from a Relational Database to DynamoDB');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Using Elasticache to Improve Database Performance');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Accessing Linux Systems Using RHEL 8');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Using Input/Output Redirection and Analyzing Text on RHEL 8');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Managing Files and Directories on RHEL 8');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Creating Simple Shell Scripts');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Managing the Boot Process on RHEL 8');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Managing Processes and Tuned Profiles on RHEL 8');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Working with Log Files and Journals on RHEL 8');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Managing Disk Partitions and Mounts on RHEL 8');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Configuring Logical Volume Management (LVM) Using RHEL 8');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Managing File Systems on RHEL 8');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Working with File and Directory Permissions on RHEL 8');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Managing Layered Local Storage with Stratis on RHEL 8');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Managing Storage Using LVM on VDO on RHEL 8');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Managing Key Services on RHEL 8 - systemd/Scheduling/Time Services');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Managing Packages and Using Application Streams in RHEL 8');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Managing the System Bootloader in RHEL 8');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Managing Basic Networking on RHEL 8');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Managing Users, Groups, and Superuser Access on RHEL 8');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Managing the Firewall on RHEL 8');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Using File Access Control Lists (ACLs) on RHEL 8');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Managing Containers on RHEL 8 Using podman');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Red Hat Certified System Administrator (EX200) - v8 Exam Challenge Lab');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Correcting Code with Cloud Debugger');
Insert into coursesid(course_id) values('Google Cloud');
Insert into courses(course_name) values('Install and Configure Monitoring Agent with Google Cloud Monitoring');
Insert into coursesid(course_id) values('Google Cloud');
Insert into courses(course_name) values('Install and Configure Logging Agent on Google Cloud');
Insert into coursesid(course_id) values('Google Cloud');
Insert into courses(course_name) values('Discovering Latency with Google Cloud Trace');
Insert into coursesid(course_id) values('Google Cloud');
Insert into courses(course_name) values('Creating Multiple Cosmos DB Containers');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Configure Azure SQL with Failover Groups');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Using SCP to Transfer Files Between Systems');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Configuring User Accounts and Permissions on a Development Server');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Creating a Backup Structure and Archiving Files');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Create a Collaborative Directory');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Managing and Troubleshooting System Services and Processes');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Reviewing System Logs and Updating the journald Configuration');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Viewing, Installing and Removing Packages Using YUM and RPM');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Validating Network Configuration and Configuring Network Services');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Practice Exam Lab for PE124');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Building a Video Transcoding Pipeline Using Elastic Transcoder');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Creating Your Own Serverless Reminder on AWS with Step Functions, API Gateway, Lambda, and S3');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Triggering Lambda from Amazon SQS');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Highly Available and Fault-Tolerant Architecture via Elastic Beanstalk');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Using AWS OpsWorks to Deploy an Application');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Building a Serverless Application Using Step Functions, API Gateway, Lambda, and S3 in AWS');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Applying Disaster Recovery Techniques in AWS');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Setting up Automatic Resource Remediation with AWS Config');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Exposing Kubernetes Pods Using Services');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Using Kubernetes Services with DNS');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Using Kubernetes Ingress');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Managing Container Storage with Kubernetes Volumes');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Using PersistentVolumes in Kubernetes');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Troubleshooting a Broken Kubernetes Cluster');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Troubleshooting a Broken Kubernetes Application');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Certified Kubernetes Administrator (CKA) Practice Exam: Part 1');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Edit Certified Kubernetes Administrator (CKA) Practice Exam: Part 2');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Certified Kubernetes Administrator (CKA) Practice Exam: Part 3');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Certified Kubernetes Administrator (CKA) Practice Exam: Part 4');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Certified Kubernetes Administrator (CKA) Practice Exam: Part 5');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Certified Kubernetes Administrator (CKA): Practice Exam: Part 6');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Certified Kubernetes Administrator (CKA) Practice Exam: Part 7');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Certified Kubernetes Administrator (CKA) Practice Exam: Part 8');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Certified Kubernetes Administrator (CKA) Practice Exam: Part 9');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Certified Kubernetes Administrator (CKA) Practice Exam: Part 10');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Initializing the Docker Environment');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Working With Prebuilt Docker Images');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Handcrafting a Container Image');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Storing Container Data In Docker Volumes');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Storing Container Data in AWS S3');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Storing Container Data in Google Cloud Storage');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Building Container Images Using Dockerfiles');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Docker Container Networking');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Dockerize a Flask Application');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Building Smaller Images with Mutli-Stage Builds');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Installing Nomad Server for Use in Dev Mode');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Installing Nomad on Three Servers');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Adding a Node to a Cluster in Nomad');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Enabling Gossip Encryption in Nomad');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Deploying a Nomad Job via CLI');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Deploying a Nomad Application in a Cluster');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Configuring Tasks for a Nomad Application');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Examining Nomad Logs');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Upgrading a Running Nomad Job on a Single Node');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Incremental Upgrades in Nomad');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('sing a Blue/Green Deployment in Nomad');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Setting an Affinity for a Nomad Job in a Cluster');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Using Spread Job Placement for a Nomad Job in a Cluster');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Moving Your Nomad Job from One Node to Another');
Insert into coursesid(course_id) values('Deployment');
Insert into courses(course_name) values('Reviewing Our Code Base with Amazon CodeGuru');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Optimizing Applications through Amazon CodeGuru?s Profiler');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Enable Archiving with Azure Blob Storage (New Version)');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('L05: Lab: Creating and Mounting Azure File Shares');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('L06: Lab: Enabling Encryption in Azure SQL');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('L04: Lab: Routing Azure Resource Logs');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Using Azure Key Vault');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Collecting IoT Core Data in GCP Pub/Sub');
Insert into coursesid(course_id) values('Google');
Insert into courses(course_name) values('Viewing Cloud IoT Core Data Using BigQuery');
Insert into coursesid(course_id) values('Google');
Insert into courses(course_name) values('Configure an HTPasswd Identity Provider in OpenShift 4');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Creating and Deleting Users in OpenShift 4');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Creating and Deleting Groups in OpenShift 4');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Creating a Service Account in OpenShift 4');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Creating a Security Context Constraint in OpenShift 4');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Querying Data in Amazon S3 with Amazon Athena');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Using Data Pipeline to Export DynamoDB Data to S3');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Setup AWS Cloudfront Distribution as an HTTP endpoint for S3 Site');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Install and Configure HashiCorp Vault on Linux');
Insert into coursesid(course_id) values('Security');
Insert into courses(course_name) values('Configure Authentication with HashiCorp Vault');
Insert into coursesid(course_id) values('Security');
Insert into courses(course_name) values('Write and Test a HashiCorp Vault Policy');
Insert into coursesid(course_id) values('Security');
Insert into courses(course_name) values('Configure and Test HashiCorp Vault REST API');
Insert into coursesid(course_id) values('Security');
Insert into courses(course_name) values('Configure SSH for HashiCorp Vault Authentication');
Insert into coursesid(course_id) values('Security');
Insert into courses(course_name) values('Implement a Logging Solution for HashiCorp Vault');
Insert into coursesid(course_id) values('Security');
Insert into courses(course_name) values('Integrating HashiCorp Vault Authentication to a Website');
Insert into coursesid(course_id) values('Security');
Insert into courses(course_name) values('Implement HashiCorp Vault API Authentication');
Insert into coursesid(course_id) values('Security');
Insert into courses(course_name) values('Implement HashiCorp Vault Authentication to MariaDB');
Insert into coursesid(course_id) values('Security');
Insert into courses(course_name) values('Modifying GRUB2 Boot Configuration (CentOS)');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Controlling System Services with Systemd');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Modifying Runlevels on Linux');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Managing AWS IAM User Permissions Using Groups and Policies');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Preventing Deletion of an Amazon S3 Bucket Using a Resource-Based Policy');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Giving an AWS Lambda Function Access to a DynamoDB Table via an Execution Role');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Limiting Privileged User Access by Setting Permissions Boundaries in AWS IAM');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Troubleshooting and Resolving AWS IAM Errors');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Monitoring, Auditing, and Logging Users and Resource Usage in AWS IAM');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Introduction to Identity and Access Management (IAM)');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Scaling EC2 Using SQS');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Using Service Principal Identity to List AD Roles');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Creating a Group and Adding Members in Azure Active Directory (AAD)');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Add, Remove and Update Tags for Resources in Azure');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Use AzCopy to Transfer Data from One Storage Account to Another');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Expire Data Based on Age in Azure Blob Storage');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Create and Restore File Share Snapshots in Azure');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Create and Manage Storage Containers in Azure Storage Explorer');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Limit Access to Azure Storage Account Using SAS URI');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Use PowerShell to Resize an Azure Virtual Machine in an Availability Set');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Install NGINX on a Linux VM in Deployment with Cloud Init');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Add Existing Data Disk to a VM in Azure');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Using Custom Images for a Virtual Machine Scale Set in Azure');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Access Windows VMs over SSL without Public IPs using Azure Bastion');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Scale Out an App Service Plan Automatically in Azure');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Create Web App from Docker Container in Azure');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Build and Run a Container using Azure ACR Tasks');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Create an AKS Cluster that uses Azure Container Instances');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Creating Multiple Subnets in Azure');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Create an Application Security Group for Two Web Servers in Azure');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Attach a Firewall to a Virtual Network in Azure');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Create a Hub-Spoke Network Topology in Azure');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Create a Virtual Network and Gateway Subnet using PowerShell');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Create a Standard Load Balancer with Azure CLI');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Restore File Share from Azure Backup to Another Storage Account');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Snapshot an Azure VM Disk using PowerShell');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Loading and Retrieving Data in Neptune');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Using Elasticache to Improve Database Performance');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Loading Data into a Redshift Cluster');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Deploying a Linux VM');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Adding and Encrypting a Storage Volume');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Deploying a Linux Virtual Machine with Cloud-Init');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Configuring iSCSI on Linux');
Insert into coursesid(course_id) values('Data Storage');
Insert into courses(course_name) values('Formatting a Packer Template in JSON');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Formatting a Packer Template in HCL2');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Setting Up Packer');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Adding Packer Plugins');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Using Packer to Create an AWS AMI');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Provisioning a Packer Image with Bash');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Adding Files to a Packer Build');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Provisioning a Packer Image with Ansible');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Provisioning a Packer Image with chef-client');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Provisioning a Packer Image with Puppet Server');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Provisioning a Packer Image with Masterless Salt');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Creating Dev and Production Images with Packer in Parallel');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Using HCL with Packer');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Debugging a Packer Build');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Building an Amazon EBS-Based Packer Image');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Building an Azure ARM-Based Packer Image');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Building a Google Compute-Backed Image with Packer');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Building a Docker Image with Packer');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Building a LXD Image with Packer');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Exploring AML Designer Transforms: Clean Missing Data');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Exploring AML Designer Transforms: Add Columns');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Exploring AML Designer Transforms: Apply Math Operation');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('AML Designer Transforms: Join Data');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Exploring AML Designer Transforms: Apply SQL Transformation');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Exploring AML Designer Transforms: Edit Metadata and Convert to Indicator values(');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Exploring AML Designer Transforms: Clip values(');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Creating Custom Modules in Azure Machine Learning Designer');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Anomaly Detection in Azure Machine Learning');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Classifications Options in Azure Machine Learning');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Feature Selection Before Training in Azure Machine Learning');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Feature Selection After Training in Azure Machine Learning');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Developing with SMOTE in Azure Machine Learning');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Email Services: Configuring Postfix');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Email Services: TLS Configuration with Postfix');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Email Services: Filter and Sort with Sieve');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Email Services: Configuring IMAP with Dovecot');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('FTP: Configure an FTP Server');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Secure Shell: SSH Configuration');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Secure Shell: Working with SSH Keys');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Creating a Topic and Subscription with Pub/Sub in Google Cloud');
Insert into coursesid(course_id) values('Google Cloud');
Insert into courses(course_name) values('Creating Our First VPC in Google Cloud');
Insert into coursesid(course_id) values('Google Cloud');
Insert into courses(course_name) values('Creating a Cloud SQL Instance in Google Cloud');
Insert into coursesid(course_id) values('Google Cloud');
Insert into courses(course_name) values('Creating a Folder and Uploading an Object in Cloud Storage');
Insert into coursesid(course_id) values('Google Cloud');
Insert into courses(course_name) values('Creating and Configuring a Compute Engine Instance');
Insert into coursesid(course_id) values('Google Cloud');
Insert into courses(course_name) values('Visualizing systemd Startups');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Using systemctl to Configure systemd');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Working with systemd Targets');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Configuring systemd Units');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Configuring systemd Timers');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Configuring systemd Journaling');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Using systemd Containers');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Using systemd cgroups');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Working with the MongoDB API in Azure Cosmos DB');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Working with the Table API in Azure Cosmos DB');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Working with the Cassandra API in Azure Cosmos DB');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Working with the Gremlin API in Azure Cosmos DB');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Implementing Stored Procedures in Azure Cosmos DB');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Optimizing Azure Cosmos DB to Reduce Cost');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Configuring Azure Cosmos DB for Global Distribution');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Web Services: Configure a Web Server for HTTPS');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Using Azure App Service Deployment Slots with Azure CLI');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Provisioning Azure Cosmos DB Resources');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Working with the Core (SQL) API in Azure Cosmos DB');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Creating a Static Website Using Amazon S3 - 2020');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Creating a Basic VPC and Associated Components - 2020');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Working with AWS VPC Flow Logs for Network Monitoring - 2020');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Getting Started with CloudFormation - 2020');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Web Services: Install Apache');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Web Services: Configure a Virtual Host on Apache');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Web Services: Create a Proxy Server');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Web Services: Create a Web Server with Nginx');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Performing a Kubernetes Upgrade with Kubeadm');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Backing up and Restoring Kubernetes Data in Etcd');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Exploring a Kubernetes Cluster With Kubectl');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Controlling Access in Kubernetes with RBAC');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Discovering Pod Resource Usage with Kubernetes Metrics');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Passing Configuration Data to a Kubernetes Container');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Building Self-Healing Containers in Kubernetes');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Using Init Containers in Kubernetes');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Assigning a Kubernetes Pod to a Specific Node');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Using DaemonSets in Kubernetes');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Using Static Pods in Kubernetes');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Managing Kubernetes Applications with Deployments');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Exploring Kubernetes Networking');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('LDAP: Managing LDAP Users');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('LDAP: Create an LDIF File');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('LDAP: Configure an OpenLDAP Server');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('LDAP: Query and Update an LDAP Server');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('NFS: Exporting and Mounting an NFS File System');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('NFS: Working with Access Restrictions');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Working With Jenkins Permissions');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Configuring Build Agents in Jenkins');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Upgrading Jenkins');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Monitoring Jenkins');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Logging System Utilization Data on a Schedule with nmon');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Installing and Configuring Webmin');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Managing Webmin Administrators Using the Webmin Console');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Installing Cockpit and Additional Modules');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Creating User Accounts and Validating the Docker Module in Cockpit');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Deploying to AWS with Terraform and Ansible');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Creating a multi-region network with VPC peering using SGs, IGW and RTs');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Deploying Jenkins Master and Worker nodes in AWS behind an ALB using Terraform & Ansible');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Creating Route53 records(Alias) to route traffic to an ALB using Terraform');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Identifying Iris Plants Using Machine Learning');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Building and Deploying An Angular App');
Insert into coursesid(course_id) values('Programing');
Insert into courses(course_name) values('Building and Using a K3s Cluster');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Troubleshooting a DNS Zone');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Troubleshooting an Apache Installation');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Troubleshooting a SAMBA Installation');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Troubleshooting an LDAP Installation');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Troubleshooting a Postfix installation');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Creating a CI/CD Pipeline on Google Cloud');
Insert into coursesid(course_id) values('Google Cloud');
Insert into courses(course_name) values('Your First Cloud Run Deployment');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Calculating Circular values( with Python Math Modules');
Insert into coursesid(course_id) values('Programming');
Insert into courses(course_name) values('Creating a Matrix Using NumPy Arrays');
Insert into coursesid(course_id) values('Programming');
Insert into courses(course_name) values('Using Pandas Data Frames and Pivot Tables in Python');
Insert into coursesid(course_id) values('Programming');
Insert into courses(course_name) values('Creating Graphs with Matplotlib');
Insert into coursesid(course_id) values('Programming');
Insert into courses(course_name) values('Editing Images with scikit-image');
Insert into coursesid(course_id) values('Programming');
Insert into courses(course_name) values('Creating a Linux VM using Azure CLI');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Create Azure Blob Storage and Upload a Blob');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('An Introduction to Azure Machine Learning Designer');
Insert into coursesid(course_id) values('Machine Learning');
Insert into courses(course_name) values('Exchange the Given For-Loop for a Comprehension');
Insert into coursesid(course_id) values('Programming');
Insert into courses(course_name) values('Building and Configuring a Kubernetes Cluster with kubeadm');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Creating and Managing a Software RAID');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Working with Kubernetes Namespaces');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Deploy and Configure Kibana for an Elasticsearch Cluster');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Define User Access Control in Elasticsearch');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Search Data in Elasticsearch');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Diagnose and Repair Elasticsearch Indices');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Aggregate Data in Elasticsearch');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Execute CRUD Operations in Elasticsearch');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Define Elasticsearch Indices');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Encrypt the Elasticsearch Client Network');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Encrypt the Elasticsearch Transport Network');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Deploy a Multi-Node Elasticsearch Cluster');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Enable Elasticsearch Cluster Monitoring');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Working with Ansible Playbooks');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Exploring AML Designer Transforms - Clean Missing Data');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Deploying WordPress and MySQL to GKE');
Insert into coursesid(course_id) values('Google Cloud');
Insert into courses(course_name) values('Using YUM for Security Updates');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Create an Amazon S3 Buckets to Manage Objects and Enable Versioning');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Protecting Script Secrets with Azure Key Vault');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Hello World in GKE');
Insert into coursesid(course_id) values('Google Cloud');
Insert into courses(course_name) values('Backup an Azure Virtual Machine with Azure Backup');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Configure Application Security Groups in Azure');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Configuring Azure Front Door Service');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Query This Berkeley DB on Linux');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Query This CSV File on Linux');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Query This XML File on Linux');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Query This JSON File on Linux');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Connect to This PostgreSQL Database on Linux');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Connect to This MariaDB Database on Linux');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Connect to This SQL Server Database on Linux');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Query This Couchbase Database on Linux');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Query This MongoDB Database on Linux');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Query This Cassandra Database on Linux');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('PostgreSQL Database Replication Demo on Linux');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Creating Swap Space on a Linux System');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Working with Systemd Mount Units');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Configure /etc/fstab to Persistently Mount a File System');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Creating Btrfs Subvolumes and Snapshots');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Configure AutoFS to Automatically Mount Filesystems');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('Building a Prometheus Server');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Collecting Linux Server Metrics with Prometheus');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Locating Time-Series Data in Prometheus');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Working with Prometheus Metric Types');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Working with Prometheus Queries');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Advanced Prometheus Queries');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Using the Prometheus HTTP API');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Building a Prometheus Console Template');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Using the Graph Library in a Prometheus Console Template');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Building a Grafana Instance to Work with Prometheus Data');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Building a Prometheus Dashboard in Grafana');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Collecting Application Metrics with Prometheus');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Docker Daemon Monitoring with Prometheus');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Docker Container Monitoring with Prometheus');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Kubernetes Monitoring with Prometheus');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Installing Prometheus Pushgateway');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Monitoring a Batch Job with Prometheus Pushgateway');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Using Prometheus Recording Rules');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Installing Prometheus Alertmanager');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Configuring Prometheus Alertmanager');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Configuring Prometheus Alertmanager for High Availability');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Configuring Prometheus Alerts');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Advanced Configuration for Prometheus Alerts');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Building a Highly Available Prometheus Setup');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Implementing Hierarchical Federation With Prometheus');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Using the Java Client Library for Prometheus');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Automatic Device Management with Device Twins in Azure');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Working with the Azure IoT Device Provisioning Service');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Provision Simulated Devices with Azure IoT and DPS');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Pipeline Jobs in Jenkins');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Declarative Pipelines in Jenkins');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Docker in Jenkins Pipelines');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Advanced Jenkins Pipelines');
Insert into coursesid(course_id) values('Containers');
Insert into courses(course_name) values('Deploying a SQL Server on Windows VM in Azure');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Deploying a SQL Server VM in Azure');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Deploying an Azure SQL Database');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Deploying an Azure Database for MySQL');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Deploying an Azure Database for MariaDB');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Deploying an Azure Database for PostgreSQL');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Creating an Azure Storage Table');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Deploying an Azure Cosmos DB Instance');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Deploying Azure Synapse Analytics Pool');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Using SQLite with Python');
Insert into coursesid(course_id) values('Programming');
Insert into courses(course_name) values('Mapping CSV Rows to Dictionaries');
Insert into coursesid(course_id) values('Programming');
Insert into courses(course_name) values('Parsing XML Documents with Python');
Insert into coursesid(course_id) values('Programming');
Insert into courses(course_name) values('Adding Logging to a Python Application');
Insert into coursesid(course_id) values('Programming');
Insert into courses(course_name) values('Working with INI Configuration Files Using configparser');
Insert into coursesid(course_id) values('Programming');
Insert into courses(course_name) values('Utilizing Dates and Times in Python');
Insert into coursesid(course_id) values('Programming');
Insert into courses(course_name) values('Working with Time Zones in Python');
Insert into coursesid(course_id) values('Programming');
Insert into courses(course_name) values('Using Python os Module');
Insert into coursesid(course_id) values('Programming');
Insert into courses(course_name) values('Working with Streams in Python');
Insert into coursesid(course_id) values('Programming');
Insert into courses(course_name) values('Creating a Virtual Network in Azure Using Azure CLI');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Configuring and Connecting to Azure Files from Windows');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Configure Azure Private Link for Blob Storage');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Configure a Load Balanced VM Scale Set in Azure');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Create a User Delegation SAS using Azure CLI');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Create a Windows Virtual Machine Image in Azure');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Configure Virtual Machine Monitoring in Azure');
Insert into coursesid(course_id) values('Azure');
Insert into courses(course_name) values('Implementing Traffic Shifting Using SAM and CodeDeploy');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Create a Custom Image with the Given Specifications');
Insert into coursesid(course_id) values('Security');
Insert into courses(course_name) values('Configure Resource Limits');
Insert into coursesid(course_id) values('Security');
Insert into courses(course_name) values('Modify Seccomp Profile of a Container');
Insert into coursesid(course_id) values('Security');
Insert into courses(course_name) values('Design a Container to Run a Proxy');
Insert into coursesid(course_id) values('Security');
Insert into courses(course_name) values('Create and Deploy an Application Back End');
Insert into coursesid(course_id) values('Security');
Insert into courses(course_name) values('Deploy a Tomcat Application Statically');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Deploy a Tomcat Application Dynamically');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Backup and Restore Tomcat');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Enable Verbose Garbage Collection');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Implementing Traffic Shifting Using SAM and CodeDeploy');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Installing Tomcat');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Adding a User to Tomcat');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Tomcat on a Different Port');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Change Tomcat for External Access');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Set up Apache as a Proxy to Tomcat');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Load Balance a Tomcat Application');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Deploy a Tomcat Application Using the GUI');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Deploy a Tomcat Application Using the CLI');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Configure Logging in Tomcat');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Create Java Heap Dumps for Tomcat');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Set Fixed Heap Size in Tomcat');
Insert into coursesid(course_id) values('DevOps');
Insert into courses(course_name) values('Creating a Serverless Application Using S3, HTTP API, Lambda, and DynamoDB');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Configuring a Custom Domain with Amazon Cognito');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('Deploying a Serverless Application Using AWS SAM');
Insert into coursesid(course_id) values('AWS');
Insert into courses(course_name) values('DNS: Configure a Caching Only Name Server');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('DNS: Working with RNDC Keys');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('DNS: Create a Forward Zone');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('DNS: Create a Reverse Zone File');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('DNS: DNS Querying');
Insert into coursesid(course_id) values('Linux');
Insert into courses(course_name) values('DNS: Create a chroot Jail');
Insert into coursesid(course_id) values('Linux');
